=== jan-ldwg/site_manager_templates/schemas/connectors.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "connectors",
  "description": "JSON document describing a list of connectors",
  "type": "array",
  "uniqueItems": true,
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "description": "Id of the connector",
        "type": "string",
        "pattern": "^[A-Za-z0-9](?:[A-Za-z0-9]|[_.](?=[A-Za-z0-9]))*_(?:f|m|h)$"
      },
      "name": {
        "description": "Name of the connector",
        "type": "string"
      },
      "gender": {
        "description": "Gender of the connector",
        "enum": ["MALE", "FEMALE", "HERMA"]
      },
      "icon": {
        "description": "Icon for use with this connector. These can be fetched as SVG icons from /icons/{id}.svg",
        "type": "string",
        "pattern": "^[A-Za-z0-9](?:[A-Za-z0-9]|[_.](?=[A-Za-z0-9]))*_(?:f|m|h)$"
      },
      "compatibleConnectors": {
        "description": "List of connectors that can mate with this connector",
        "type": "array",
        "uniqueItems": true,
        "items": {
          "type": "string",
          "pattern": "^[A-Za-z0-9](?:[A-Za-z0-9]|[_.](?=[A-Za-z0-9]))*_(?:f|m|h)$"
        }
      }
    },
    "required": ["id", "name", "gender", "icon", "compatibleConnectors"],
    "additionalProperties": false
  }
}

=== jan-ldwg/site_manager_templates/connectors/connectors.json
[
  {
    "id": "BNC_f",
    "name": "BNC 75 Ohm female",
    "gender": "FEMALE",
    "icon": "BNC_f",
    "compatibleConnectors": ["BNC_m"]
  },
  {
    "id": "BNC_m",
    "name": "BNC 75 Ohm male",
    "gender": "MALE",
    "icon": "BNC_m",
    "compatibleConnectors": ["BNC_f"]
  },
  {
    "id": "HD_BNC_f",
    "name": "HD-BNC 75 Ohm female",
    "gender": "FEMALE",
    "icon": "HD_BNC_f",
    "compatibleConnectors": ["HD_BNC_m"]
  },
  {
    "id": "HD_BNC_m",
    "name": "HD-BNC 75 Ohm male",
    "gender": "MALE",
    "icon": "HD_BNC_m",
    "compatibleConnectors": ["HD_BNC_f"]
  },
  {
    "id": "DSUB9p_f",
    "name": "D-Sub 9p female",
    "gender": "FEMALE",
    "icon": "DSUB9p_f",
    "compatibleConnectors": ["DSUB9p_m"]
  },
  {
    "id": "DSUB9p_m",
    "name": "D-Sub 9p male",
    "gender": "MALE",
    "icon": "DSUB9p_m",
    "compatibleConnectors": ["DSUB9p_f"]
  },
  {
    "id": "DSUB25p_f",
    "name": "D-Sub 25p female",
    "gender": "FEMALE",
    "icon": "DSUB25p_f",
    "compatibleConnectors": ["DSUB25p_m"]
  },
  {
    "id": "DSUB25p_m",
    "name": "D-Sub 25p male",
    "gender": "MALE",
    "icon": "DSUB25p_m",
    "compatibleConnectors": ["DSUB25p_f"]
  },
  {
    "id": "DSUB37p_f",
    "name": "D-Sub 37p female",
    "gender": "FEMALE",
    "icon": "DSUB37p_f",
    "compatibleConnectors": ["DSUB37p_m"]
  },
  {
    "id": "DSUB37p_m",
    "name": "D-Sub 37p male",
    "gender": "MALE",
    "icon": "DSUB37p_m",
    "compatibleConnectors": ["DSUB37p_f"]
  },
  {
    "id": "DSUB15p_HD_f",
    "name": "D-Sub HD 15p female",
    "gender": "FEMALE",
    "icon": "DSUB15p_HD_f",
    "compatibleConnectors": ["DSUB15p_HD_m"]
  },
  {
    "id": "DSUB15p_HD_m",
    "name": "D-Sub HD 15p male",
    "gender": "MALE",
    "icon": "DSUB15p_HD_m",
    "compatibleConnectors": ["DSUB15p_HD_f"]
  },
  {
    "id": "DSUB15p_MICRO_f",
    "name": "Micro D-Sub 15p female",
    "gender": "FEMALE",
    "icon": "DSUB15p_MICRO_f",
    "compatibleConnectors": ["DSUB15p_MICRO_m"]
  },
  {
    "id": "DSUB15p_MICRO_m",
    "name": "Micro D-Sub 15p male",
    "gender": "MALE",
    "icon": "DSUB15p_MICRO_m",
    "compatibleConnectors": ["DSUB15p_MICRO_f"]
  },
  {
    "id": "DIN5p_f",
    "name": "DIN 5p 180° female",
    "gender": "FEMALE",
    "icon": "DIN5p_f",
    "compatibleConnectors": ["DIN5p_m"]
  },
  {
    "id": "DIN5p_m",
    "name": "DIN 5p 180° male",
    "gender": "MALE",
    "icon": "DIN5p_m",
    "compatibleConnectors": ["DIN5p_f"]
  },
  {
    "id": "ETHERCON_f",
    "name": "ETHERCON female",
    "gender": "FEMALE",
    "icon": "ETHERCON_f",
    "compatibleConnectors": ["RJ45_m", "ETHERCON_m"]
  },
  {
    "id": "ETHERCON_m",
    "name": "ETHERCON male",
    "gender": "MALE",
    "icon": "ETHERCON_m",
    "compatibleConnectors": ["ETHERCON_f"]
  },
  {
    "id": "SC_SPLX_PC_SM_f",
    "name": "SC Simplex, PC, SM female",
    "gender": "FEMALE",
    "icon": "SCSPLX_f",
    "compatibleConnectors": ["SC_SPLX_PC_SM_m"]
  },
  {
    "id": "SC_SPLX_PC_SM_m",
    "name": "SC Simplex, PC, SM male",
    "gender": "MALE",
    "icon": "SCSPLX_m",
    "compatibleConnectors": ["SC_SPLX_PC_SM_f"]
  },
  {
    "id": "SC_SPLX_PC_MM_f",
    "name": "SC Simplex, PC, MM female",
    "gender": "FEMALE",
    "icon": "SCSPLX_f",
    "compatibleConnectors": ["SC_SPLX_PC_MM_m"]
  },
  {
    "id": "SC_SPLX_PC_MM_m",
    "name": "SC Simplex, PC, MM male",
    "gender": "MALE",
    "icon": "SCSPLX_m",
    "compatibleConnectors": ["SC_SPLX_PC_MM_f"]
  },
  {
    "id": "SC_DPLX_PC_SM_f",
    "name": "SC Duplex, PC, SM female",
    "gender": "FEMALE",
    "icon": "SCDPLX_f",
    "compatibleConnectors": ["SC_DPLX_PC_SM_m"]
  },
  {
    "id": "SC_DPLX_PC_SM_m",
    "name": "SC Duplex, PC, SM male",
    "gender": "MALE",
    "icon": "SCDPLX_m",
    "compatibleConnectors": ["SC_DPLX_PC_SM_f"]
  },
  {
    "id": "SC_DPLX_PC_MM_f",
    "name": "SC Duplex, PC, MM female",
    "gender": "FEMALE",
    "icon": "SCDPLX_f",
    "compatibleConnectors": ["SC_DPLX_PC_MM_m"]
  },
  {
    "id": "SC_DPLX_PC_MM_m",
    "name": "SC Duplex, PC, MM male",
    "gender": "MALE",
    "icon": "SCDPLX_m",
    "compatibleConnectors": ["SC_DPLX_PC_MM_f"]
  },
  {
    "id": "LC_SPLX_PC_SM_f",
    "name": "LC Simplex, PC, SM female",
    "gender": "FEMALE",
    "icon": "LCSPLX_f",
    "compatibleConnectors": ["LC_SPLX_PC_SM_m"]
  },
  {
    "id": "LC_SPLX_PC_SM_m",
    "name": "LC Simplex, PC, SM male",
    "gender": "MALE",
    "icon": "LCSPLX_m",
    "compatibleConnectors": ["LC_SPLX_PC_SM_f"]
  },
  {
    "id": "LC_DPLX_PC_MM_f",
    "name": "LC Duplex, PC, MM female",
    "gender": "FEMALE",
    "icon": "LCDPLX_f",
    "compatibleConnectors": ["LC_DPLX_PC_MM_m", "LC_DPLX_UPC_MM_m"]
  },
  {
    "id": "LC_DPLX_PC_MM_m",
    "name": "LC Duplex, PC, MM male",
    "gender": "MALE",
    "icon": "LCDPLX_m",
    "compatibleConnectors": ["LC_DPLX_PC_MM_f", "LC_DPLX_UPC_MM_f"]
  },
  {
    "id": "LC_DPLX_UPC_MM_f",
    "name": "LC Duplex, UPC, MM female",
    "gender": "FEMALE",
    "icon": "LCDPLX_f",
    "compatibleConnectors": ["LC_DPLX_UPC_MM_m", "LC_DPLX_PC_MM_m"]
  },
  {
    "id": "LC_DPLX_UPC_MM_m",
    "name": "LC Duplex, UPC, MM male",
    "gender": "MALE",
    "icon": "LCDPLX_m",
    "compatibleConnectors": ["LC_DPLX_UPC_MM_f", "LC_DPLX_PC_MM_f"]
  },
  {
    "id": "LC_DPLX_PC_SM_f",
    "name": "LC Duplex, PC, SM female",
    "gender": "FEMALE",
    "icon": "LCDPLX_f",
    "compatibleConnectors": ["LC_DPLX_PC_SM_m", "LC_DPLX_UPC_SM_m"]
  },
  {
    "id": "LC_DPLX_PC_SM_m",
    "name": "LC Duplex, PC, SM male",
    "gender": "MALE",
    "icon": "LCDPLX_m",
    "compatibleConnectors": ["LC_DPLX_PC_SM_f", "LC_DPLX_UPC_SM_f"]
  },
  {
    "id": "LC_DPLX_UPC_SM_f",
    "name": "LC Duplex, UPC, SM female",
    "gender": "FEMALE",
    "icon": "LCDPLX_f",
    "compatibleConnectors": ["LC_DPLX_UPC_SM_m", "LC_DPLX_PC_SM_m"]
  },
  {
    "id": "LC_DPLX_UPC_SM_m",
    "name": "LC Duplex, UPC, SM male",
    "gender": "MALE",
    "icon": "LCDPLX_m",
    "compatibleConnectors": ["LC_DPLX_UPC_SM_f", "LC_DPLX_PC_SM_f"]
  },
  {
    "id": "LC_DPLX_APC_SM_f",
    "name": "LC Duplex, APC, SM female",
    "gender": "FEMALE",
    "icon": "LCDPLX_f",
    "compatibleConnectors": ["LC_DPLX_APC_SM_m"]
  },
  {
    "id": "LC_DPLX_APC_SM_m",
    "name": "LC Duplex, APC, SM male",
    "gender": "MALE",
    "icon": "LCDPLX_m",
    "compatibleConnectors": ["LC_DPLX_APC_SM_f"]
  },
  {
    "id": "MPO_8_PC_MM_m",
    "name": "MPO8, PC, MM male",
    "gender": "MALE",
    "icon": "MPO8_m",
    "compatibleConnectors": ["MPO_8_PC_MM_f", "MPO_12_PC_MM_f"]
  },
  {
    "id": "MPO_8_PC_MM_f",
    "name": "MPO8, PC, MM female",
    "gender": "FEMALE",
    "icon": "MPO8_f",
    "compatibleConnectors": ["MPO_8_PC_MM_m", "MPO_12_PC_MM_m"]
  },
  {
    "id": "MPO_12_PC_MM_m",
    "name": "MPO12, PC, MM male",
    "gender": "MALE",
    "icon": "MPO12_m",
    "compatibleConnectors": ["MPO_12_PC_MM_f", "MPO_8_PC_MM_f"]
  },
  {
    "id": "MPO_12_PC_MM_f",
    "name": "MPO12, PC, MM female",
    "gender": "FEMALE",
    "icon": "MPO12_f",
    "compatibleConnectors": ["MPO_12_PC_MM_m", "MPO_8_PC_MM_m"]
  },
  {
    "id": "MPO_8_APC_SM_m",
    "name": "MPO8, APC, SM male",
    "gender": "MALE",
    "icon": "MPO8_m",
    "compatibleConnectors": ["MPO_8_APC_SM_f", "MPO_12_APC_SM_f"]
  },
  {
    "id": "MPO_8_APC_SM_f",
    "name": "MPO8, APC, SM female",
    "gender": "FEMALE",
    "icon": "MPO8_f",
    "compatibleConnectors": ["MPO_8_APC_SM_m", "MPO_12_APC_SM_m"]
  },
  {
    "id": "MPO_12_APC_SM_m",
    "name": "MPO12, APC, SM male",
    "gender": "MALE",
    "icon": "MPO12_m",
    "compatibleConnectors": ["MPO_12_APC_SM_f", "MPO_8_APC_SM_f"]
  },
  {
    "id": "MPO_12_APC_SM_f",
    "name": "MPO12, APC, SM female",
    "gender": "FEMALE",
    "icon": "MPO12_f",
    "compatibleConnectors": ["MPO_12_APC_SM_m", "MPO_8_APC_SM_m"]
  },
  {
    "id": "OPC_DUO_PC_MM_m",
    "name": "opticalCON DUO, PC, MM male",
    "gender": "MALE",
    "icon": "OPC_DUO_m",
    "compatibleConnectors": [
      "OPC_DUO_PC_MM_f",
      "LC_DPLX_PC_MM_f",
      "LC_DPLX_UPC_MM_f"
    ]
  },
  {
    "id": "OPC_DUO_PC_MM_f",
    "name": "opticalCON DUO, PC, MM female",
    "gender": "FEMALE",
    "icon": "OPC_DUO_f",
    "compatibleConnectors": [
      "OPC_DUO_PC_MM_m",
      "LC_DPLX_PC_MM_m",
      "LC_DPLX_UPC_MM_m"
    ]
  },
  {
    "id": "OPC_DUO_PC_SM_m",
    "name": "opticalCON DUO, PC, SM male",
    "gender": "MALE",
    "icon": "OPC_DUO_m",
    "compatibleConnectors": [
      "OPC_DUO_APC_SM_f",
      "LC_DPLX_PC_SM_f",
      "LC_DPLX_UPC_SM_f"
    ]
  },
  {
    "id": "OPC_DUO_PC_SM_f",
    "name": "opticalCON DUO, PC, SM female",
    "gender": "FEMALE",
    "icon": "OPC_DUO_f",
    "compatibleConnectors": [
      "OPC_DUO_APC_SM_m",
      "LC_DPLX_PC_SM_m",
      "LC_DPLX_UPC_SM_m"
    ]
  },
  {
    "id": "OPC_DUO_APC_SM_m",
    "name": "opticalCON DUO, APC, SM male",
    "gender": "MALE",
    "icon": "OPC_DUO_m",
    "compatibleConnectors": ["OPC_DUO_APC_SM_f", "LC_DPLX_APC_SM_f"]
  },
  {
    "id": "OPC_DUO_APC_SM_f",
    "name": "opticalCON DUO, APC, SM female",
    "gender": "FEMALE",
    "icon": "OPC_DUO_f",
    "compatibleConnectors": ["OPC_DUO_APC_SM_m", "LC_DPLX_APC_SM_m"]
  },
  {
    "id": "RJ45_f",
    "name": "RJ45 female",
    "gender": "FEMALE",
    "icon": "RJ45_f",
    "compatibleConnectors": ["RJ45_m"]
  },
  {
    "id": "RJ45_m",
    "name": "RJ45 male",
    "gender": "MALE",
    "icon": "RJ45_m",
    "compatibleConnectors": ["RJ45_f", "ETHERCON_f"]
  },
  {
    "id": "USB2.0A_f",
    "name": "USB 2.0 A female",
    "gender": "FEMALE",
    "icon": "USB2.0A_f",
    "compatibleConnectors": ["USB2.0A_m", "USB3.0A_m"]
  },
  {
    "id": "USB2.0A_m",
    "name": "USB 2.0 A male",
    "gender": "MALE",
    "icon": "USB2.0A_m",
    "compatibleConnectors": ["USB2.0A_f", "USB3.0A_f"]
  },
  {
    "id": "USB2.0B_f",
    "name": "USB 2.0 B female",
    "gender": "FEMALE",
    "icon": "USB2.0B_f",
