=== jan-ldwg/site_manager_templates/schemas/devicetype.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "devicetype",
  "description": "JSON document describing a new device type",
  "type": "object",
  "properties": {
    "version": {
      "description": "Version number of the template. Minor version must be increased with every change. Major version must only be changed when targeting a different API version.",
      "type": "string",
      "pattern": "^\\d{1,2}\\.\\d{1,2}$"
    },
    "id": {
      "description": "Id of the device type. Consists of id of manufacturer followed by id of device type. See documentation for rules.",
      "type": "string",
      "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$",
      "maxLength": 48
    },
    "name": {
      "description": "Name of the device as given by manufacturer",
      "type": "string",
      "maxLength": 256
    },
    "manufacturerId": {
      "description": "Id of the manufacturer of the device type.",
      "type": "string",
      "pattern": "^(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])$",
      "maxLength": 16
    },
    "orderCode": {
      "description": "Order code for the device type as used by the manufacturer.",
      "type": ["string", "null"]
    },
    "orderNumber": {
      "description": "Order number for the device type as used by the manufacturer.",
      "type": ["string", "null"]
    },
    "climateLoad": {
      "description": "The maximum heat dissipation of the device type.",
      "type": ["integer", "null"],
      "minimum": 0
    },
    "portTypes": {
      "description": "List of all types of ports on the device type.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "Name of the port, as printed on the device.",
            "type": "string"
          },
          "direction": {
            "description": "Direction of the port type. See documentation for explainations of the possible values.",
            "enum": [
              "IN",
              "OUT",
              "INOUT",
              "BIDI",
              "UP",
              "DOWN",
              "FRONT",
              "REAR"
            ]
          },
          "connectorId": {
            "description": "Id of the connector.",
            "type": "string",
            "pattern": "^[A-Za-z0-9](?:[A-Za-z0-9]|[_.](?=[A-Za-z0-9]))*_(?:f|m|h)$"
          },
          "compatibleSignalTypes": {
            "description": "List of signal types that are compatible with this port.",
            "type": "array",
            "items": {
              "type": "string",
              "pattern": "^(?!.*--)(?:[a-z](?:[a-z-]{0,14}[a-z])?_)?[A-Z0-9]+(?:_[A-Z0-9]+)*$"
            },
            "uniqueItems": true
          }
        },
        "required": [
          "name",
          "direction",
          "connectorId",
          "compatibleSignalTypes"
        ],
        "additionalProperties": false
      }
    },
    "moduleSlotTypes": {
      "description": "List of all types of module slots on the device type.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "Name of the module slot, as labeled on the device.",
            "type": "string"
          },
          "compatibleModuleSlotFormFactors": {
            "description": "List of module slot factors that can physically fit into the slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
            }
          },
          "compatibleModuleTypes": {
            "description": "List of module types that are guranteed by the manufacturer to work in this slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$"
            }
          },
          "incompatibleModuleTypes": {
            "description": "List of module types that are guranteed by the manufacturer not work in this module slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$"
            }
          }
        },
        "required": [
          "name",
          "compatibleModuleSlotFormFactors",
          "compatibleModuleTypes",
          "incompatibleModuleTypes"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": ["version", "id", "name", "manufacturerId"],
  "additionalProperties": false
}

=== jan-ldwg/site_manager_templates/devicetypes/skaarhoj/skaarhoj-ptz-extreme.json
{
  "version": "1.0",
  "id": "skaarhoj-ptz-extreme",
  "name": "PTZ Extreme",
  "manufacturerId": "skaarhoj",
  "orderCode": null,
  "orderNumber": "5714074002710",
  "climateLoad": 7,
  "portTypes": [
    {
      "name": "",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T"]
    },
    {
      "name": "",
      "direction": "OUT",
      "connectorId": "USB2.0A_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2"]
    },
    {
      "name": "",
      "direction": "IN",
      "connectorId": "USB2.0B_MICRO_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2"]
    }
  ],
  "moduleSlotTypes": []
}

=== jan-ldwg/site_manager_templates/devicetypes/weytec/weytec-16-slot-chassis-4u.json
{
  "version": "1.0",
  "id": "weytec-16-slot-chassis-4u",
  "name": "16 Slot Chassis 4U",
  "manufacturerId": "weytec",
  "orderCode": null,
  "orderNumber": "23175-MX",
  "climateLoad": 400,
  "portTypes": [
    {
      "name": "LAN",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX"]
    },
    {
      "name": "Service",
      "direction": "IN",
      "connectorId": "USB2.0B_MINI_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2"]
    },
    {
      "name": "Power Out 1",
      "direction": "OUT",
      "connectorId": "DIN4p_f",
      "compatibleSignalTypes": ["12v_dc_power"]
    },
    {
      "name": "Power Out 2",
      "direction": "OUT",
      "connectorId": "DIN4p_f",
      "compatibleSignalTypes": ["12v_dc_power"]
    }
  ],
  "moduleSlotTypes": [
    {
      "name": "Slot 1",
      "compatibleModuleSlotFormFactors": ["weytec_din_card"],
      "compatibleModuleTypes": ["weytec-ip-remote-ii-dp-tx-dual"],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 2",
      "compatibleModuleSlotFormFactors": ["weytec_din_card"],
      "compatibleModuleTypes": ["weytec-ip-remote-ii-dp-tx-dual"],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 3",
      "compatibleModuleSlotFormFactors": ["weytec_din_card"],
      "compatibleModuleTypes": ["weytec-ip-remote-ii-dp-tx-dual"],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 4",
      "compatibleModuleSlotFormFactors": ["weytec_din_card"],
      "compatibleModuleTypes": ["weytec-ip-remote-ii-dp-tx-dual"],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 5",
      "compatibleModuleSlotFormFactors": ["weytec_din_card"],
      "compatibleModuleTypes": ["weytec-ip-remote-ii-dp-tx-dual"],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 6",
      "compatibleModuleSlotFormFactors": ["weytec_din_card"],
      "compatibleModuleTypes": ["weytec-ip-remote-ii-dp-tx-dual"],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 7",
      "compatibleModuleSlotFormFactors": ["weytec_din_card"],
      "compatibleModuleTypes": ["weytec-ip-remote-ii-dp-tx-dual"],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 8",
      "compatibleModuleSlotFormFactors": ["weytec_din_card"],
      "compatibleModuleTypes": ["weytec-ip-remote-ii-dp-tx-dual"],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 9",
      "compatibleModuleSlotFormFactors": ["weytec_din_card"],
      "compatibleModuleTypes": ["weytec-ip-remote-ii-dp-tx-dual"],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 10",
      "compatibleModuleSlotFormFactors": ["weytec_din_card"],
      "compatibleModuleTypes": ["weytec-ip-remote-ii-dp-tx-dual"],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 11",
      "compatibleModuleSlotFormFactors": ["weytec_din_card"],
      "compatibleModuleTypes": ["weytec-ip-remote-ii-dp-tx-dual"],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 12",
      "compatibleModuleSlotFormFactors": ["weytec_din_card"],
      "compatibleModuleTypes": ["weytec-ip-remote-ii-dp-tx-dual"],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 13",
      "compatibleModuleSlotFormFactors": ["weytec_din_card"],
      "compatibleModuleTypes": ["weytec-ip-remote-ii-dp-tx-dual"],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 14",
      "compatibleModuleSlotFormFactors": ["weytec_din_card"],
      "compatibleModuleTypes": ["weytec-ip-remote-ii-dp-tx-dual"],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 15",
      "compatibleModuleSlotFormFactors": ["weytec_din_card"],
      "compatibleModuleTypes": ["weytec-ip-remote-ii-dp-tx-dual"],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 16",
      "compatibleModuleSlotFormFactors": ["weytec_din_card"],
      "compatibleModuleTypes": ["weytec-ip-remote-ii-dp-tx-dual"],
      "incompatibleModuleTypes": []
    }
  ]
}

=== jan-ldwg/site_manager_templates/devicetypes/genelec/genelec-8351bp.json
{
  "version": "1.0",
  "id": "genelec-8351bp",
  "name": "8351BP",
  "manufacturerId": "genelec",
  "orderCode": "8351BP",
  "orderNumber": null,
  "climateLoad": 200,
  "portTypes": [
    {
      "name": "DIGITAL IN AES/EBU",
      "direction": "IN",
      "connectorId": "XLR3p_f",
      "compatibleSignalTypes": ["AES3"]
    },
    {
      "name": "DIGITAL THRU AES/EBU",
      "direction": "OUT",
      "connectorId": "XLR3p_m",
      "compatibleSignalTypes": ["AES3"]
    },
    {
      "name": "ANALOG IN",
      "direction": "IN",
      "connectorId": "XLR3p_f",
      "compatibleSignalTypes": ["AUDIO_BAL_ANA"]
    },
    {
      "name": "GLM NETWORK",
      "direction": "IN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["genelec_GLM"]
    },
    {
      "name": "GLM NETWORK",
      "direction": "OUT",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["genelec_GLM"]
    }
  ]
}

=== jan-ldwg/site_manager_templates/devicetypes/directout/directout-exboxrav.json
{
  "version": "1.0",
  "id": "directout-exboxrav",
  "name": "EXBOX.RAV",
  "manufacturerId": "directout",
  "orderCode": null,
  "orderNumber": "DOEXB2020",
  "climateLoad": 9,
  "portTypes": [
    {
      "name": "01 (PoE)",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T"]
    },
    {
      "name": "02",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T"]
    },
    {
      "name": "03",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T"]
    },
    {
      "name": "04",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T"]
    },
    {
      "name": "MADI BNC IN",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["MADI_CU"]
    },
    {
      "name": "MADI BNC OUT",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["MADI_CU"]
    },
    {
      "name": "MADI SC IN",
      "direction": "IN",
      "connectorId": "SC_SPLX_PC_MM_f",
      "compatibleSignalTypes": ["MADI_MM_1310"]
    },
    {
      "name": "MADI SC OUT",
      "direction": "OUT",
      "connectorId": "SC_SPLX_PC_MM_f",
      "compatibleSignalTypes": ["MADI_MM_1310"]
    }
  ],
  "moduleSlotTypes": [
    {
      "name": "MADI SFP I/O",
      "compatibleModuleSlotFormFactors": ["sfp"],
      "compatibleModuleTypes": [
        "directout-sfp-madi-bnc",
        "directout-sfp-madi-mm",
        "directout-sfp-madi-sm",
        "directout-usbmadi"
      ],
      "incompatibleModuleTypes": []
    }
  ]
}

=== jan-ldwg/site_manager_templates/devicetypes/directout/directout-breaktoutan8.json
{
  "version": "1.0",
  "id": "directout-breakoutan8",
  "name": "BREAKOUT.AN8",
  "manufacturerId": "directout",
  "orderCode": null,
  "orderNumber": "DOBOB0989",
  "climateLoad": 0,
  "portTypes": [
    {
      "name": "ANALOG IN 01..08",
      "direction": "IN",
      "connectorId": "DSUB25p_f",
      "compatibleSignalTypes": ["AES59_ANA"]
    },
    {
      "name": "ANALOG OUT 01..08",
      "direction": "OUT",
      "connectorId": "DSUB25p_f",
      "compatibleSignalTypes": ["AES59_ANA"]
    },
    {
      "name": "1",
      "direction": "IN",
      "connectorId": "XLR3p_f",
      "compatibleSignalTypes": ["AUDIO_BAL_ANA", "AUDIO_MIC", "AUDIO_MIC_48V"]
    },
    {
      "name": "2",
      "direction": "IN",
      "connectorId": "XLR3p_f",
      "compatibleSignalTypes": ["AUDIO_BAL_ANA", "AUDIO_MIC", "AUDIO_MIC_48V"]
    },
    {
      "name": "3",
      "direction": "IN",
      "connectorId": "XLR3p_f",
      "compatibleSignalTypes": ["AUDIO_BAL_ANA", "AUDIO_MIC", "AUDIO_MIC_48V"]
    },
    {
      "name": "4",
      "direction": "IN",
      "connectorId": "XLR3p_f",
      "compatibleSignalTypes": ["AUDIO_BAL_ANA", "AUDIO_MIC", "AUDIO_MIC_48V"]
    },
    {
      "name": "5",
      "direction": "IN",
      "connectorId": "XLR3p_f",
      "compatibleSignalTypes": ["AUDIO_BAL_ANA", "AUDIO_MIC", "AUDIO_MIC_48V"]
    },
    {
      "name": "6",
      "direction": "IN",
      "connectorId": "XLR3p_f",
      "compatibleSignalTypes": ["AUDIO_BAL_ANA", "AUDIO_MIC", "AUDIO_MIC_48V"]
    },
    {
      "name": "7",
      "direction": "IN",
      "connectorId": "XLR3p_f",
      "compatibleSignalTypes": ["AUDIO_BAL_ANA", "AUDIO_MIC", "AUDIO_MIC_48V"]
    },
    {
      "name": "8",
      "direction": "IN",
      "connectorId": "XLR3p_f",
      "compatibleSignalTypes": ["AUDIO_BAL_ANA", "AUDIO_MIC", "AUDIO_MIC_48V"]
    },
    {
      "name": "1",
      "direction": "OUT",
      "connectorId": "XLR3p_m",
      "compatibleSignalTypes": ["AUDIO_BAL_ANA"]
    },
    {
      "name": "2",
      "direction": "OUT",
      "connectorId": "XLR3p_m",
      "compatibleSignalTypes": ["AUDIO_BAL_ANA"]
    },
    {
      "name": "3",
      "direction": "OUT",
      "connectorId": "XLR3p_m",
      "compatibleSignalTypes": ["AUDIO_BAL_ANA"]
    },
    {
      "name": "4",
      "direction": "OUT",
      "connectorId": "XLR3p_m",
      "compatibleSignalTypes": ["AUDIO_BAL_ANA"]
    },
    {
      "name": "5",
      "direction": "OUT",
      "connectorId": "XLR3p_m",
      "compatibleSignalTypes": ["AUDIO_BAL_ANA"]
    },
    {
      "name": "6",
      "direction": "OUT",
      "connectorId": "XLR3p_m",
      "compatibleSignalTypes": ["AUDIO_BAL_ANA"]
    },
    {
      "name": "7",
      "direction": "OUT",
      "connectorId": "XLR3p_m",
      "compatibleSignalTypes": ["AUDIO_BAL_ANA"]
    },
    {
      "name": "8",
      "direction": "OUT",
      "connectorId": "XLR3p_m",
      "compatibleSignalTypes": ["AUDIO_BAL_ANA"]
    }
  ],
  "moduleSlotTypes": []
}

=== jan-ldwg/site_manager_templates/devicetypes/riedel/riedel-rsp-1216hl-7p.json
{
  "version": "1.0",
  "id": "riedel-rsp-1216hl-7p",
  "name": "RSP-1216HL",
  "manufacturerId": "riedel",
  "orderCode": null,
  "orderNumber": "9301244",
  "climateLoad": 15,
  "portTypes": [
    {
      "name": "ETH 1",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["10BASE_T", "100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "ETH 2",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["10BASE_T", "100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "MGNT",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["10BASE_T", "100BASE_TX"]
    },
    {
      "name": "EXP",
      "direction": "OUT",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["riedel_EXPANSION"]
    },
    {
      "name": "MATRIX 1",
      "direction": "IN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["riedel_ARTIST_G2_CAT"]
    },
    {
      "name": "MATRIX 2",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["riedel_ARTIST_G2_COAX"]
    },
    {
      "name": "DP",
      "direction": "OUT",
      "connectorId": "DISPLAYPORT_f",
      "compatibleSignalTypes": []
    },
    {
      "name": "GPI-IN",
      "direction": "IN",
      "connectorId": "DSUB9p_f",
      "compatibleSignalTypes": ["GPIO"]
    },
    {
      "name": "GPI-OUT",
      "direction": "OUT",
      "connectorId": "DSUB9p_m",
      "compatibleSignalTypes": ["GPIO"]
    },
    {
      "name": "AUDIO A",
      "direction": "BIDI",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": []
    },
    {
      "name": "AUDIO B",
      "direction": "BIDI",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": []
    },
    {
      "name": "HEADSET A",
      "direction": "IN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": []
    },
    {
      "name": "HEADSET B",
      "direction": "IN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": []
    },
    {
      "name": "USB",
      "direction": "OUT",
      "connectorId": "USBC_f",
      "compatibleSignalTypes": ["USB_2"]
    },
    {
      "name": "USB (front)",
      "direction": "OUT",
      "connectorId": "USB2.0A_f",
      "compatibleSignalTypes": ["USB_2"]
    },
    {
      "name": "",
      "direction": "IN",
      "connectorId": "XLR7p_m",
      "compatibleSignalTypes": []
    }
  ],
  "moduleSlotTypes": [
    {
      "name": "ETH 3",
      "compatibleModuleSlotFormFactors": ["sfp"],
      "compatibleModuleTypes": [],
      "incompatibleModuleTypes": []
    },
    {
      "name": "ETH 4",
      "compatibleModuleSlotFormFactors": ["sfp"],
      "compatibleModuleTypes": [],
      "incompatibleModuleTypes": []
    }
  ]
}

=== jan-ldwg/site_manager_templates/devicetypes/lawo/lawo-crystal-tabletop-light.json
{
  "version": "1.0",
  "id": "lawo-crystal-tabletop-light",
  "name": "crystal Tabletop Light",
  "manufacturerId": "lawo",
  "orderCode": null,
  "orderNumber": "715/30-10",
  "climateLoad": 40,
  "portTypes": [
    {
      "name": "ETHERNET",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX"]
    },
    {
      "name": "CAN A",
      "direction": "BIDI",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["CAN_1M"]
    },
    {
      "name": "CAN B",
      "direction": "BIDI",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["CAN_500K"]
    }
  ],
  "moduleSlotTypes": [
    {
      "name": "",
      "compatibleModuleSlotFormFactors": [],
      "compatibleModuleTypes": [
        "lawo-crystal-fader-module-light",
        "lawo-crystal-main-module-light"
      ],
      "incompatibleModuleTypes": []
    }
  ]
}

=== jan-ldwg/site_manager_templates/devicetypes/dell/dell-r360-4x35.json
{
  "version": "1.0",
  "id": "dell-r360-4x35",
  "name": "PowerEdge R360 4x3,5 Zoll",
  "manufacturerId": "dell",
  "orderCode": null,
  "orderNumber": null,
  "climateLoad": 770,
  "portTypes": [
    {
      "name": "USB (Front)",
      "direction": "OUT",
      "connectorId": "USB2.0A_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2"]
    },
    {
      "name": "iDRAC Direct",
      "direction": "IN",
      "connectorId": "USB2.0B_MICRO_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2"]
    },
    {
      "name": "IOIOI",
      "direction": "IN",
      "connectorId": "DSUB9p_m",
      "compatibleSignalTypes": ["RS_232"]
    },
    {
      "name": "iDRAC",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["10BASE_T", "100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "1",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["10BASE_T", "100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "2",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["10BASE_T", "100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "VGA",
      "direction": "IN",
      "connectorId": "DSUB15p_HD_f",
      "compatibleSignalTypes": ["VGA", "DVI_I", "DVI_A"]
    },
    {
      "name": "USB+",
      "direction": "OUT",
      "connectorId": "USB3.0A_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2"]
    },
    {
      "name": "SS USB",
      "direction": "OUT",
      "connectorId": "USB3.0A_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2", "USB_32_GEN1X1"]
    }
  ],
  "moduleSlotTypes": [
    {
      "name": "Slot-1",
      "compatibleModuleSlotFormFactors": [
        "pcie-x1-hl-lp",
        "pcie-x4-hl-lp",
        "pcie-x8-hl-lp",
        "pcie-x16-hl-lp"
      ],
      "compatibleModuleTypes": [],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot-2",
      "compatibleModuleSlotFormFactors": [
        "pcie-x1-hl-lp",
        "pcie-x4-hl-lp",
        "pcie-x8-hl-lp",
        "pcie-x16-hl-lp"
      ],
      "compatibleModuleTypes": [],
      "incompatibleModuleTypes": []
    }
  ]
}
