=== jan-ldwg/site_manager_templates/schemas/devicetype.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "devicetype",
  "description": "JSON document describing a new device type",
  "type": "object",
  "properties": {
    "version": {
      "description": "Version number of the template. Minor version must be increased with every change. Major version must only be changed when targeting a different API version.",
      "type": "string",
      "pattern": "^\\d{1,2}\\.\\d{1,2}$"
    },
    "id": {
      "description": "Id of the device type. Consists of id of manufacturer followed by id of device type. See documentation for rules.",
      "type": "string",
      "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$",
      "maxLength": 48
    },
    "name": {
      "description": "Name of the device as given by manufacturer",
      "type": "string",
      "maxLength": 256
    },
    "manufacturerId": {
      "description": "Id of the manufacturer of the device type.",
      "type": "string",
      "pattern": "^(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])$",
      "maxLength": 16
    },
    "orderCode": {
      "description": "Order code for the device type as used by the manufacturer.",
      "type": ["string", "null"]
    },
    "orderNumber": {
      "description": "Order number for the device type as used by the manufacturer.",
      "type": ["string", "null"]
    },
    "climateLoad": {
      "description": "The maximum heat dissipation of the device type.",
      "type": ["integer", "null"],
      "minimum": 0
    },
    "portTypes": {
      "description": "List of all types of ports on the device type.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "Name of the port, as printed on the device.",
            "type": "string"
          },
          "direction": {
            "description": "Direction of the port type. See documentation for explainations of the possible values.",
            "enum": [
              "IN",
              "OUT",
              "INOUT",
              "BIDI",
              "UP",
              "DOWN",
              "FRONT",
              "REAR"
            ]
          },
          "connectorId": {
            "description": "Id of the connector.",
            "type": "string",
            "pattern": "^[A-Za-z0-9](?:[A-Za-z0-9]|[_.](?=[A-Za-z0-9]))*_(?:f|m|h)$"
          },
          "compatibleSignalTypes": {
            "description": "List of signal types that are compatible with this port.",
            "type": "array",
            "items": {
              "type": "string",
              "pattern": "^(?!.*--)(?:[a-z](?:[a-z-]{0,14}[a-z])?_)?[A-Z0-9]+(?:_[A-Z0-9]+)*$"
            },
            "uniqueItems": true
          }
        },
        "required": [
          "name",
          "direction",
          "connectorId",
          "compatibleSignalTypes"
        ],
        "additionalProperties": false
      }
    },
    "moduleSlotTypes": {
      "description": "List of all types of module slots on the device type.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "Name of the module slot, as labeled on the device.",
            "type": "string"
          },
          "compatibleModuleSlotFormFactors": {
            "description": "List of module slot factors that can physically fit into the slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
            }
          },
          "compatibleModuleTypes": {
            "description": "List of module types that are guranteed by the manufacturer to work in this slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$"
            }
          },
          "incompatibleModuleTypes": {
            "description": "List of module types that are guranteed by the manufacturer not work in this module slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$"
            }
          }
        },
        "required": [
          "name",
          "compatibleModuleSlotFormFactors",
          "compatibleModuleTypes",
          "incompatibleModuleTypes"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": ["version", "id", "name", "manufacturerId"],
  "additionalProperties": false
}

=== jan-ldwg/site_manager_templates/devicetypes/telestream/telestream-mpp-100.json
{
  "version": "1.0",
  "id": "telestream-mpp-100",
  "name": "PRISM MPP-100",
  "manufacturerId": "telestream",
  "orderCode": null,
  "orderNumber": null,
  "climateLoad": 160,
  "portTypes": [
    {
      "name": "LAN",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T"]
    },
    {
      "name": "REF IN",
      "direction": "IN",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": ["BLACK_BURST", "TRI_SYNC"]
    },
    {
      "name": "REF OUT",
      "direction": "OUT",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": ["BLACK_BURST", "TRI_SYNC", "PPS"]
    },
    {
      "name": "SDI IN 1",
      "direction": "IN",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "SDI OUT 1",
      "direction": "OUT",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "SDI IN 2",
      "direction": "IN",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "SDI OUT 2",
      "direction": "OUT",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "SDI IN 3",
      "direction": "IN",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "SDI OUT 3",
      "direction": "OUT",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "SDI IN 4",
      "direction": "IN",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "SDI OUT 4",
      "direction": "OUT",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "AUX OUT",
      "direction": "OUT",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "DP1",
      "direction": "OUT",
      "connectorId": "DISPLAYPORT_f",
      "compatibleSignalTypes": ["DP"]
    },
    {
      "name": "DP2",
      "direction": "OUT",
      "connectorId": "DISPLAYPORT_f",
      "compatibleSignalTypes": ["DP"]
    },
    {
      "name": "USB (Rear)",
      "direction": "OUT",
      "connectorId": "USB3.0A_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2", "USB_32_GEN1X1"]
    },
    {
      "name": "USB (Rear)",
      "direction": "OUT",
      "connectorId": "USB3.0A_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2", "USB_32_GEN1X1"]
    },
    {
      "name": "GPIO",
      "direction": "IN",
      "connectorId": "DSUB15p_MICRO_f",
      "compatibleSignalTypes": ["GPIO"]
    },
    {
      "name": "USB (Front)",
      "direction": "OUT",
      "connectorId": "USB3.0A_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2", "USB_32_GEN1X1"]
    },
    {
      "name": "USB (Front)",
      "direction": "OUT",
      "connectorId": "USB3.0A_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2", "USB_32_GEN1X1"]
    },
    {
      "name": "Headphones",
      "direction": "OUT",
      "connectorId": "TRS_35_f",
      "compatibleSignalTypes": ["PHONES_ANA"]
    }
  ]
}

=== jan-ldwg/site_manager_templates/devicetypes/directout/directout-mavena.json
{
  "version": "1.0",
  "id": "directout-mavena",
  "name": "MAVEN.A",
  "manufacturerId": "directout",
  "orderCode": null,
  "orderNumber": "DOMVA0002",
  "climateLoad": 55,
  "portTypes": [
    {
      "name": "MGMT",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T"]
    },
    {
      "name": "WCK IN",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["WCLK"]
    },
    {
      "name": "WCK OUT",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["WCLK"]
    },
    {
      "name": "USB",
      "direction": "IN",
      "connectorId": "USBC_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2"]
    },
    {
      "name": "USB",
      "direction": "OUT",
      "connectorId": "USB2.0A_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2"]
    },
    {
      "name": "GPIO",
      "direction": "INOUT",
      "connectorId": "DSUB9p_f",
      "compatibleSignalTypes": ["GPIO"]
    },
    {
      "name": "PHONES 1",
      "direction": "OUT",
      "connectorId": "TRS_635_f",
      "compatibleSignalTypes": ["PHONES_ANA"]
    },
    {
      "name": "PHONES 2",
      "direction": "OUT",
      "connectorId": "TRS_35_f",
      "compatibleSignalTypes": ["PHONES_ANA"]
    }
  ],
  "moduleSlotTypes": [
    {
      "name": "MADI 1",
      "compatibleModuleSlotFormFactors": ["sfp"],
      "compatibleModuleTypes": [
        "directout-sfp-madi-bnc",
        "directout-sfp-madi-mm",
        "directout-sfp-madi-sm",
        "directout-usbmadi"
      ],
      "incompatibleModuleTypes": []
    },
    {
      "name": "MADI 2",
      "compatibleModuleSlotFormFactors": ["sfp"],
      "compatibleModuleTypes": [
        "directout-sfp-madi-bnc",
        "directout-sfp-madi-mm",
        "directout-sfp-madi-sm",
        "directout-usbmadi"
      ],
      "incompatibleModuleTypes": []
    },
    {
      "name": "SLOT A",
      "compatibleModuleSlotFormFactors": ["directout-a-slot"],
      "compatibleModuleTypes": [],
      "incompatibleModuleTypes": []
    },
    {
      "name": "SLOT C1",
      "compatibleModuleSlotFormFactors": ["directout-c-slot"],
      "compatibleModuleTypes": [],
      "incompatibleModuleTypes": []
    },
    {
      "name": "SLOT C2",
      "compatibleModuleSlotFormFactors": ["directout-c-slot"],
      "compatibleModuleTypes": [],
      "incompatibleModuleTypes": []
    }
  ]
}

=== jan-ldwg/site_manager_templates/devicetypes/lake-people/lake-people-g103-p-mkii-broadcast-230v.json
{
  "version": "1.0",
  "id": "lake-people-g103-p-mkii-broadcast-230v",
  "name": "G103-P MKII Broadcast Version (230 V)",
  "manufacturerId": "lake-people",
  "orderCode": null,
  "orderNumber": "1008574",
  "climateLoad": 58,
  "portTypes": [
    {
      "name": "BALANCED IN LEFT",
      "direction": "IN",
      "connectorId": "XLR3p_f",
      "compatibleSignalTypes": ["AUDIO_BAL_ANA"]
    },
    {
      "name": "BALANCED IN RIGHT",
      "direction": "IN",
      "connectorId": "XLR3p_f",
      "compatibleSignalTypes": ["AUDIO_BAL_ANA"]
    },
    {
      "name": "Headphones",
      "direction": "OUT",
      "connectorId": "TRS_635_f",
      "compatibleSignalTypes": ["PHONES_ANA"]
    },
    {
      "name": "Headphones",
      "direction": "OUT",
      "connectorId": "TRS_635_f",
      "compatibleSignalTypes": ["PHONES_ANA"]
    }
  ]
}

=== jan-ldwg/site_manager_templates/devicetypes/neumann/neumann-bcm-104.json
{
  "version": "1.0",
  "id": "neumann-bcm-104",
  "name": "BCM 104",
  "manufacturerId": "neumann",
  "orderCode": null,
  "orderNumber": "008483",
  "climateLoad": 0,
  "portTypes": [
    {
      "name": "Out",
      "direction": "OUT",
      "connectorId": "XLR3p_m",
      "compatibleSignalTypes": ["AUDIO_MIC_48V"]
    }
  ]
}

=== jan-ldwg/site_manager_templates/devicetypes/directout/directout-hcontrol8.json
{
  "version": "1.0",
  "id": "directout-hcontrol8",
  "name": "HCONTROL.8",
  "manufacturerId": "directout",
  "orderCode": null,
  "orderNumber": "DOCTRL001",
  "climateLoad": 36,
  "portTypes": [
    {
      "name": "ETHERNET",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["10BASE_T", "100BASE_TX"]
    },
    {
      "name": "USB TO HOST",
      "direction": "IN",
      "connectorId": "USBC_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2"]
    }
  ],
  "moduleSlotTypes": []
}

=== jan-ldwg/site_manager_templates/devicetypes/directout/directout-breakoutaesid.json
{
  "version": "1.0",
  "id": "directout-breakoutaesid",
  "name": "BREAKOUT.AESid",
  "manufacturerId": "directout",
  "orderCode": null,
  "orderNumber": "DOBOB0988",
  "climateLoad": 0,
  "portTypes": [
    {
      "name": "AES INPUT/OUTPUT 01..08",
      "direction": "BIDI",
      "connectorId": "DSUB25p_f",
      "compatibleSignalTypes": ["AES59_DIGI_IO"]
    },
    {
      "name": "AES INPUT/OUTPUT 09..16",
      "direction": "BIDI",
      "connectorId": "DSUB25p_f",
      "compatibleSignalTypes": ["AES59_DIGI_IO"]
    },
    {
      "name": "AES INPUT/OUTPUT 17..24",
      "direction": "BIDI",
      "connectorId": "DSUB25p_f",
      "compatibleSignalTypes": ["AES59_DIGI_IO"]
    },
    {
      "name": "AES INPUT/OUTPUT 25..32",
      "direction": "BIDI",
      "connectorId": "DSUB25p_f",
      "compatibleSignalTypes": ["AES59_DIGI_IO"]
    },
    {
      "name": "AES INPUT 01/02",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES INPUT 03/04",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES INPUT 05/06",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES INPUT 07/08",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES INPUT 09/10",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES INPUT 11/12",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES INPUT 13/14",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES INPUT 15/16",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES INPUT 17/18",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES INPUT 19/20",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES INPUT 21/22",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES INPUT 23/24",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES INPUT 25/26",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES INPUT 27/28",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES INPUT 29/30",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES INPUT 31/32",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES OUTPUT 01/02",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES OUTPUT 03/04",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES OUTPUT 05/06",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES OUTPUT 07/08",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES OUTPUT 09/10",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES OUTPUT 11/12",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES OUTPUT 13/14",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES OUTPUT 15/16",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES OUTPUT 17/18",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES OUTPUT 19/20",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES OUTPUT 21/22",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES OUTPUT 23/24",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES OUTPUT 25/26",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES OUTPUT 27/28",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES OUTPUT 29/30",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    },
    {
      "name": "AES OUTPUT 31/32",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["AES3ID"]
    }
  ],
  "moduleSlotTypes": []
}

=== jan-ldwg/site_manager_templates/devicetypes/black-box/black-box-emd2002pe-dp-t.json
{
  "version": "1.1",
  "id": "black-box-emd2002pe-dp-t",
  "name": "EMD2002PE-DP-T",
  "manufacturerId": "black-box",
  "orderCode": null,
  "orderNumber": "EMD2002PE-DP-T",
  "climateLoad": 36,
  "portTypes": [
    {
      "name": "LAN 1",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["10BASE_T", "100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "DP1",
      "direction": "IN",
      "connectorId": "DISPLAYPORT_f",
      "compatibleSignalTypes": ["DP"]
    },
    {
      "name": "DP2",
      "direction": "IN",
      "connectorId": "DISPLAYPORT_f",
      "compatibleSignalTypes": ["DP"]
    },
    {
      "name": "USB",
      "direction": "IN",
      "connectorId": "USB2.0B_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2"]
    },
    {
      "name": "3.5mm Audio",
      "direction": "IN",
      "connectorId": "TRS_35_f",
      "compatibleSignalTypes": ["AUDIO_UNBAL_ANA_STEREO"]
    },
    {
      "name": "Console",
      "direction": "IN",
      "connectorId": "USB2.0B_MICRO_f",
      "compatibleSignalTypes": []
    }
  ],
  "moduleSlotTypes": [
    {
      "name": "LAN 2",
      "compatibleModuleSlotFormFactors": ["sfp"],
      "compatibleModuleTypes": [],
      "incompatibleModuleTypes": []
    }
  ]
}

=== jan-ldwg/site_manager_templates/devicetypes/hp/hp-universal-dock-g2.json
{
  "version": "1.1",
  "id": "hp-universal-dock-g2",
  "name": "USB-C/A Universal Dock G2",
  "manufacturerId": "hp",
  "orderCode": null,
  "orderNumber": "5TW13AA#ABB",
  "climateLoad": 0,
  "portTypes": [
    {
      "name": "DOCKING",
      "direction": "IN",
      "connectorId": "USBC_f",
      "compatibleSignalTypes": [
        "USB_1",
        "USB_11",
        "USB_2",
        "USB_32_GEN1X1",
        "DP"
      ]
    },
    {
      "name": "LAN",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T"]
    },
    {
      "name": "DP",
      "direction": "OUT",
      "connectorId": "DISPLAYPORT_f",
      "compatibleSignalTypes": ["DP", "HDMI", "DVI_I", "DVI_D"]
    },
    {
      "name": "DP",
      "direction": "OUT",
      "connectorId": "DISPLAYPORT_f",
      "compatibleSignalTypes": ["DP", "HDMI", "DVI_I", "DVI_D"]
    },
    {
      "name": "HDMI",
      "direction": "OUT",
      "connectorId": "HDMI_A_f",
      "compatibleSignalTypes": ["HDMI", "DVI_D", "DVI_I"]
    },
    {
      "name": "Headset",
      "direction": "BIDI",
      "connectorId": "TRRS_35_f",
      "compatibleSignalTypes": ["AUDIO_UNBAL_ANA_HEADSET"]
    },
    {
      "name": "USB (back)",
      "direction": "OUT",
      "connectorId": "USB3.0A_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2", "USB_32_GEN1X1"]
    },
    {
      "name": "USB (back)",
      "direction": "OUT",
      "connectorId": "USB3.0A_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2", "USB_32_GEN1X1"]
    },
    {
      "name": "USB (side)",
      "direction": "OUT",
      "connectorId": "USB3.0A_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2", "USB_32_GEN1X1"]
    },
    {
      "name": "USB (side)",
      "direction": "OUT",
      "connectorId": "USB3.0A_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2", "USB_32_GEN1X1"]
    },
    {
      "name": "USB (front)",
      "direction": "OUT",
      "connectorId": "USBC_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2", "USB_32_GEN1X1"]
    }
  ]
}
